variable "POC_USECASE2_GlueJob_Name" {}
variable "POC_USECASE2_GlueJob_Description" {}
variable "POC_USECASE2_GlueJob_Command_Name" {}
variable "POC_USECASE2_GlueJob_Script_Runtime" {}
variable "iam_role_arn" {}
variable "POC_USECASE2_BUCKET_FOLDER_Glue_Script" {}
variable "POC_USECASE2_BUCKET" {}
variable "POC_USECASE2_BUCKET_NAME" {}
variable "POC_USECASE2_SNS_arn" {}
variable "public_ip" {}