variable "common_tags" {}
variable "POC_USECASE2_BUCKET_NAME" {}
variable "POC_USECASE2_BUCKET_KEY_FOLDER" {}
variable "CSV_FILE_PATH" {}
variable "POC_USECASE2_Lambda" {}
variable "POC_USECASE2_Lambda_invoke_arn" {}
variable "POC_USECASE2_LambdaArn_Coded" {}
variable "POC_USECASE2_Lambda_Name" {}
variable "POC_USECASE2_BUCKET_FOLDER_Glue_Script" {}